version: '3'

services:
  nginx:
    container_name: proba-nginx
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./.docker/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      probafeladat-network:
    ports:
      - "9090:90"
    restart: always
  php:
    image: php:8.2-fpm
    build:
      context: ./
      dockerfile: ./.docker/DockerFile
    container_name: proba-php
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    command: bash -c "sleep 10 && php spark migrate && php spark cronjob:run DataFetchService && php-fpm"
    depends_on:
      - mysql
      - phpmyadmin
    networks:
      - probafeladat-network
  mysql:
    image: mysql:5.7
    container_name: proba-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - probafeladat-network

  phpmyadmin:
    container_name: proba-pma
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '1010:80'
    env_file:
      - .env
    networks:
      - probafeladat-network
networks:
  probafeladat-network:

