FROM php:8.2-fpm
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# Git
RUN apt-get update && \
    apt-get install -y git nano cron

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Permissions
WORKDIR /var/www/html
COPY . /var/www/html
RUN chmod -R 755 writable/ && chown -R www-data:www-data writable/

RUN composer install
RUN php spark migrate

WORKDIR /var/www/html
