FROM php:8.2-fpm
# Git
RUN apt-get update && \
    apt-get install -y libicu-dev git nano cron

RUN docker-php-ext-install mysqli pdo pdo_mysql intl && docker-php-ext-enable pdo_mysql intl

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Permissions
WORKDIR /var/www/html
COPY . /var/www/html

RUN composer install
RUN chmod -R 755 writable/ && chown -R www-data:www-data writable/

WORKDIR /var/www/html
